language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - DJANGO="Django>=2.0.0,<2.1.0"
  - DJANGO="Django>=2.1.0,<2.2.0"

before_install:
  - pip install poetry nox

install:
  - pip install -q $DJANGO
  - poetry install

script:
  - coverage run runtests.py
